### PR TITLE
fix(blog): add breadcrumbs to posts

### LINKED ISSUE #268: Blog posts are missing breadcrumbs (parents)
### What information was incorrect, unhelpful, or incomplete?

Breadcrumbs are missing on Blog post pages:

- https://fred.review.mdn.allizom.net/en-US/blog/color-models-humans-devices/
- https://fred.review.mdn.allizom.net/en-US/blog/color-models-humans-devices/index.json

### What did you expect to see?

Expected to see breadcrumbs, with two entries:

- MDN Blog
- (Current blog post)

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by caugner**
### Description

Adds missing breadcrumbs to Blog posts.

### Motivation

Consistency.

### Related issues and pull requests

Fixes https://github.com/mdn/rari/issues/268.

### CODE REVIEW

File: crates/rari-doc/src/pages/build.rs [hunk 1]
```diff
@@ -337,6 +337,7 @@ fn build_blog_post(post: &BlogPost) -> Result<BuiltPage, DocError> {
         live_samples,
         ..
     } = build_content(post)?;
+    let parents = parents(post);
```
Comment (caugner) [inline crates/rari-doc/src/pages/build.rs:340]:
```suggestion
```

File: crates/rari-doc/src/pages/build.rs [hunk 2]
```diff
@@ -354,6 +355,10 @@ fn build_blog_post(post: &BlogPost) -> Result<BuiltPage, DocError> {
         locale: post.locale(),
         blog_meta: Some((&post.meta).into()),
         page_title: page_title(post, false)?,
+        common: CommonJsonData {
+            parents,
```
Comment (caugner) [inline crates/rari-doc/src/pages/build.rs:359]:
```suggestion
            description: Some(post.meta.description.clone()),
            parents: parents(post),
```

**Review by argl — APPROVED** [review]
thanks!
