### PR TITLE
fix(css-syntax): distinguish formal syntax scopes

### LINKED ISSUE #196: CSS rect() formal syntax is missing CSS Shapes syntax
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/rect

### What specific section or headline is this issue about?

_No response_

### What information was incorrect, unhelpful, or incomplete?

The formal syntax and spec use commas. The explanation and examples don't. The spec / formal syntax don't include `round` as a parameter of the function. 

The basic shapes spec omits commas and includes round.

### What did you expect to see?

content, formal syntax, and spec being in sync.
We should likely update the page to reflect the current specification, and add a note where we include the legacy formal syntax. 

### Do you have any supporting links, references, or citations?

https://drafts.fxtf.org/css-masking-1/#funcdef-clip-rect (legacy)
https://www.w3.org/TR/css-shapes-1/#typedef-basic-shape (newer spec)

### Do you have anything more you want to share?

The page is using the to the legacy `rect()` function which was used solely by the now deprecated `clip` property.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/basic-shape/rect`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/rect
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/basic-shape/rect/index.md
* Last commit: https://github.com/mdn/content/commit/a075805de90029b65fa5cfcc8ea43737728320f5
* Document last modified: 2025-02-13T17:34:12.000Z

</details>

### PR DESCRIPTION
**Pull request by argl**
### Description

This adds support for scoping of css syntax entries to get rid of ambiguities/overlaps, for example the `rect()` function exists in the CSS masking and CSS shapes realms, with different definitions.

### Motivation

Showing correct information. 

### Additional information

There are a handful of duplicate entries in the data, limiting the problem somehow: 
`["fit-content()", "rect()", "repeat()", "scale()", "scaleX()", "scaleY()", "type()"]`

Running a [diff](https://gist.github.com/argl/b36b8c4b0ba3151001a94cbcd67a43b5) between old and fixed versions emits two pages actually changed, now showing the correct formal syntax:
`/en-US/docs/Web/CSS/basic-shape/rect`
`/en-us/docs/web/css/fit-content_function`

#### Before

`/en-US/docs/Web/CSS/basic-shape/rect`

image

#### After

`/en-US/docs/Web/CSS/basic-shape/rect`

image

#### Competing `rect()` definition

`en-US/docs/Web/CSS/clip`

image

#### Before

`en-US/docs/Web/CSS/fit-content_function`

image

#### After

`en-US/docs/Web/CSS/fit-content_function`

image

#### Competing `length` definition (example):

`en-US/docs/Web/CSS/Reference/Properties/max-height`

image

### Related issues and pull requests

Fixes #196

### CODE REVIEW

File: crates/css-syntax/src/syntax.rs [hunk 1]
```diff
@@ -67,46 +67,112 @@ pub enum CssType<'a> {
...
+            }
+        }
+    }
+
+    if let Some(at_rule) = CSS_REF
+        .atrules
+        .get("__global_scope__")
+        .unwrap()
+        .get(at_rule_name)
+    {
```
Comment (caugner) [inline crates/css-syntax/src/syntax.rs]: Is this not already covered by the loop above?

File: crates/css-syntax/src/syntax.rs [hunk 2]
```diff
@@ -140,59 +206,49 @@ impl Syntax {
...
+    }
 }
 
-fn get_syntax_internal(typ: CssType, top_level: bool) -> SyntaxLine {
+fn get_syntax_internal(typ: CssType, browser_compat: Option<&str>, top_level: bool) -> SyntaxLine {
     match typ {
         CssType::ShorthandProperty(name) | CssType::Property(name) => {
             let trimmed = name
                 .trim_start_matches(['<', '\''])
                 .trim_end_matches(['\'', '>']);
```
Comment (caugner) [inline crates/css-syntax/src/syntax.rs]: I wonder if this pre-processing shouldn't be part of `get_property_syntax()`, `get_type_syntax()`, etc.

File: crates/rari-doc/src/html/code.rs [hunk 3]
```diff
@@ -112,7 +112,7 @@ pub fn code_blocks(html: &mut Html) -> Option<Vec<Code>> {
     for code in examples {
         for node_id in &code.node_ids {
             if let Some(mut node) = html.tree.get_mut(*node_id) {
-                if let Node::Element(ref mut el) = node.value() {
+                if let Node::Element(el) = node.value() {
```
Comment (caugner) [inline crates/rari-doc/src/html/code.rs]: These changes look unrelated, possibly due to the Rust bump?

File: crates/rari-doc/src/templ/templs/csssyntax.rs [hunk 4]
```diff
@@ -58,6 +58,7 @@ pub fn csssyntax(name: Option<String>) -> Result<String, DocError> {
 
     Ok(render_formal_syntax(
         SyntaxInput::Css(typ),
+        env.browser_compat.first().map(|s| s.as_str()),
```
Comment (caugner) [inline crates/rari-doc/src/templ/templs/csssyntax.rs]: Do you know if there are any pages using the formal syntax macro with multiple browser-compat frontmatter values?

File: crates/css-syntax/src/syntax.rs [hunk 5]
```diff
@@ -631,6 +555,14 @@ pub enum SyntaxInput<'a> {
     Css(CssType<'a>),
 }
 
+fn scope_from_browser_compat(browser_compat: Option<&str>) -> Option<&str> {
+    if let Some(bc) = browser_compat {
```
Comment (caugner) [inline crates/css-syntax/src/syntax.rs]: Nit: Maybe exclude non-CSS keys explicitly, to avoid surprises.

```suggestion
    if let Some(bc) = browser_compat && bc.starts_with("css.") {
```

File: crates/css-syntax/src/syntax.rs [hunk 6]
```diff
@@ -631,6 +555,14 @@ pub enum SyntaxInput<'a> {
...
+        bc.split(".").collect::<Vec<&str>>().get(2).copied()
```
Comment (caugner) [inline crates/css-syntax/src/syntax.rs]: Nit: Maybe instead:

```suggestion
        bc.splitn(3, ".").nth(2)
```

File: crates/rari-doc/src/templ/templs/csssyntax.rs [hunk 7]
```diff
@@ -56,6 +56,10 @@ pub fn csssyntax(name: Option<String>) -> Result<String, DocError> {
 
     let sources_prefix = l10n_json_data("Template", "formal_syntax_footer", env.locale)?;
 
+    if env.browser_compat.len() > 1 {
+        warn!("Multiple browser-compat entries found. CSS formal syntax will be rendered using the first entry as the scope: {}", env.browser_compat.first().unwrap());
```
Comment (caugner) [inline crates/rari-doc/src/templ/templs/csssyntax.rs]: Nit: I think we can log all entries, to make it easier for the reader to understand what the other entries are.

```suggestion
        warn!("Multiple browser-compat entries found. CSS formal syntax will use the scope of the first entry: {}", env.browser_compat);
```

**Review by caugner — APPROVED** [review]
